spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: "${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs"

  cloud:
    gateway:
      routes:
        - id: payroll_route
          uri: lb://PAYROLL
          predicates:
            - Path=/payroll/**
          filters:
            - name: CircuitBreaker
              args:
                name: payrollCircuitBreaker
                fallbackUri: forward:/fallback # Redireciona se falhar conforme regras do resilience4j
        - id: worker_route
          uri: lb://WORKER
          predicates:
            - Path=/worker/**
          filters:
            - name: CircuitBreaker
              args:
                name: workerCircuitBreaker
                fallbackUri: forward:/fallback # Redireciona se falhar conforme regras do resilience4j
        - id: user_route
          uri: lb://USER
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback # Redireciona se falhar conforme regras do resilience4j
        - id: oauth_route
          uri: lb://OAUTH
          predicates:
            - Path=/oauth/**
          filters:
            - name: CircuitBreaker
              args:
                name: oauthCircuitBreaker
                fallbackUri: forward:/fallback # Redireciona se falhar conforme regras do resilience4j

      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    circuitbreaker:
      resilience4j:
        configs:
          default:
            failureRateThreshold: 50          # Percentual de falhas necessário (50%)
            slidingWindowSize: 10             # Tamanho da janela deslizante para calcular a taxa de falhas (10 requisições)
            minimumNumberOfCalls: 5           # Número mínimo de requisições para começar a calcular a taxa de falhas
            permittedNumberOfCallsInHalfOpenState: 3  # Quantas chamadas permitidas no estado half-open
            waitDurationInOpenState: 10s      # Quanto tempo o Circuit Breaker permanece em estado aberto
            slidingWindowType: COUNT_BASED    # Janela de contagem de requisições
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    io.netty.resolver.dns: TRACE
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
  url: http://localhost:8081
  client-id: gateway
  realm: lucasjorge
  admin-url: ${keycloak.url}/admin/realms/${keycloak.realm}
  realms-url: ${keycloak.url}/realms/${keycloak.realm}
  auth:
    openid-token: ${keycloak.realms-url}/protocol/openid-connect/token
    client-secret: A1ZnEjtHH73zLU9WVvGxHnEM24RKa3tb