

spring:
  application:
    name: API Gateway
  cloud:
    gateway:
      routes:
        - id: rota-exemplo
          uri: http://httpbin.org:80 # URL do serviço que será acessado
          predicates:
            - Path=/get # Roteia requisições com caminho "/get"
          filters:
            - AddRequestHeader=X-Request-Example, ValorExemplo # Adiciona um cabeçalho customizado
