  version: '3'
  networks:
    local-kafka:
      driver: bridge

  services:
    zookeeper:
      image: confluentinc/cp-zookeeper:7.0.1
      networks:
        - local-kafka
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

    broker:
      image: confluentinc/cp-kafka:7.0.1
      networks:
        - local-kafka
      ports:
        # To learn about configuring Kafka for access across networks see
        # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
        - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_L://0.0.0.0:9092,
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_L://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

    kafka-ui:
      image: provectuslabs/kafka-ui
      networks:
        - local-kafka
      depends_on:
        - broker
      ports:
        - "7777:8080"
      restart: always
      environment:
        - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=broker:29092
        - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
